apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
spec:
  project: default
  destination:
    namespace: my-project
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/yaakovsm/nginx-argo-demo.git
    targetRevision: main
    path: nginx-chart
    helm:
      valueFiles:
        - environments/prod/values-prod.yaml
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
