apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
spec:
  destination:
    namespace: my-project
    server: https://kubernetes.default.svc
  source:
    path: '/home/yaakovsm/bootcamp/practice/nginx-argocd/manifests'
    repoURL: https://github.com/yaakovsm/nginx-argo-demo.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      enabled: true
